// export { default as facial_hair_1 } from "./facial_hair_1.svg";
export { default as facial_hair_2 } from "./facial_hair_2.svg";
export { default as facial_hair_3 } from "./facial_hair_3.svg";
export { default as facial_hair_4 } from "./facial_hair_4.svg";
export { default as facial_hair_5 } from "./facial_hair_5.svg";
export { default as facial_hair_6 } from "./facial_hair_6.svg";
export { default as facial_hair_7 } from "./facial_hair_7.svg";
export { default as facial_hair_8 } from "./facial_hair_8.svg";
export { default as facial_hair_9 } from "./facial_hair_9.svg";
export { default as facial_hair_10 } from "./facial_hair_10.svg";
export { default as facial_hair_11 } from "./facial_hair_11.svg";
export { default as facial_hair_12 } from "./facial_hair_12.svg";
export { default as facial_hair_13 } from "./facial_hair_13.svg";
export { default as facial_hair_14 } from "./facial_hair_14.svg";
export { default as facial_hair_15 } from "./facial_hair_15.svg";
export { default as facial_hair_16 } from "./facial_hair_16.svg";
export { default as facial_hair_17 } from "./facial_hair_17.svg";
